name: audiolive
displayName: Zego AudioLive-语音互动
description:
redirectUrl: https://itunes.apple.com/cn/app/audiolive-%E8%AF%AD%E9%9F%B3%E4%BA%92%E5%8A%A8/id1460660023
installers:
changelog:
logo: ./logo.jpg
tags:
screenshots:
